unit TestuManipuladorContato;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uManipuladorContato, uContato;


type
  IManipuladorContato = interface
  ['{56ECC7A4-8A40-40C9-9913-54D935EDF447}']
    procedure TestSalvarContato;
    procedure TestExcluirContato;
  end;

type
  TestTManipuladorContato = class(TTestCase)
  strict private
    FManipuladorContato: TManipuladorContato;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSalvarContato;
    procedure TestExcluirContato;
  end;

implementation

procedure TestTManipuladorContato.SetUp;
begin
  FManipuladorContato := TManipuladorContato.Create;
end;

procedure TestTManipuladorContato.TearDown;
begin
  FManipuladorContato.Free;
  FManipuladorContato := nil;
end;

procedure TestTManipuladorContato.TestSalvarContato;
begin
  FManipuladorContato.SalvarContato;
  // TODO: Validate method results
end;

procedure TestTManipuladorContato.TestExcluirContato;
var
  CdContato: Integer;
begin
  // TODO: Setup method call parameters
  FManipuladorContato.ExcluirContato(CdContato);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTManipuladorContato.Suite);
end.

